name: Auto Publish NPM
on: push
jobs:
  publish:
    name: Build, bump & publish to npm
    runs-on: ubuntu-latest
    container: httptoolkit/act-build-base:v3.0.0
    steps:
        - uses: actions/setup-node@v3
          with:
            node-version: '16.x'
            registry-url: 'https://registry.npmjs.org'
        - name: Bump version & push
          run: |
            git config --global user.name 'Automated publish'
            git config --global user.email 'ArdaGnsrn@users.noreply.github.com'
            npm version patch
            git push && git push --tags
        - run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
